-- begin CUBAAT_SSH_CREDENTIAL
alter table CUBAAT_SSH_CREDENTIAL add constraint FK_CUBAAT_SSH_CREDENTIAL_PRIVATE_KEY foreign key (PRIVATE_KEY_ID) references SYS_FILE(ID)^
create index IDX_CUBAAT_SSH_CREDENTIAL_PRIVATE_KEY on CUBAAT_SSH_CREDENTIAL (PRIVATE_KEY_ID)^
-- end CUBAAT_SSH_CREDENTIAL
